src/BangazonUserAuth/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BangazonUserAuth.Models;
using BangazonUserAuth.Data;
using BangazonUserAuth.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace BangazonUserAuth.Controllers
{
    // Class Name: CustomersController
    // Authors: Chris Smalley, Zack Repass
    // Purpose of the class: The purpose of this class is to manage the methods that will produce the data and functionality needed for all of the views in the user interface related to customers.
    // Methods in Class: New(), Overloaded New(Customer customer) ShoppingCart(), Payment(), OrderCompleted().
    public class CustomersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        private ApplicationDbContext newContext;
        public CustomersController(UserManager<ApplicationUser> userManager, ApplicationDbContext ctx1)
        {
            _userManager = userManager;
            newContext = ctx1;
        }

        // This task retrieves the currently authenticated user
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        //Method Name: ShoppingCart
        //Purpose of the Method: 
            //Gets all LineItems on active order and give data to the returned View. 
            //Gets all PaymentTypes of selected Customer and give data to the returned View.
            //This method returns the Customer/ShoppingCart view.
        //Arguments in Method: None.
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> ShoppingCart()
        {
            var user = await GetCurrentUserAsync();
            var activeOrder = await newContext.Order.Where(o => o.IsCompleted == false && o.User==user).SingleOrDefaultAsync();

            ShoppingCartViewModel model = new ShoppingCartViewModel(_userManager, newContext);

            if (activeOrder == null)
            {
               var product = new Product(){Description="You have no products in your cart!", Name=""};
                model.Products = new List<Product>();
                model.Products.Add(product);
                model.ListOfPaymentTypes = newContext.PaymentType
               .Where(pt => pt.User == user)
               .AsEnumerable()
               .Select(pt => new SelectListItem
               {
                   Text = $"{pt.FirstName} {pt.LastName} {pt.Processor} {pt.ExpirationDate}",
                   Value = pt.PaymentTypeId.ToString()
               }).ToList();

                model.ListOfPaymentTypes.Insert(0, new SelectListItem

                {
                    Text = "Choose Payment Type"
                });
                return View(model);
            }

            List<LineItem> LineItemsOnActiveOrder = newContext.LineItem.Where(li => li.OrderId == activeOrder.OrderId).ToList();
            
            List<Product> ListOfProducts = new List<Product>();

            double CartTotal = 0;

            for(var i = 0; i < LineItemsOnActiveOrder.Count(); i++)
            {
                ListOfProducts.Add(newContext.Product.Where(p => p.ProductId == LineItemsOnActiveOrder[i].ProductId).SingleOrDefault());
                CartTotal += newContext.Product.Where(p => p.ProductId == LineItemsOnActiveOrder[i].ProductId).SingleOrDefault().Price;
            }

            model.ListOfPaymentTypes = newContext.PaymentType
               .Where(pt => pt.User == user)
               .AsEnumerable()
               .Select(pt => new SelectListItem
               {
                   Text = $"{pt.FirstName} {pt.LastName} {pt.Processor} {pt.ExpirationDate}",
                   Value = pt.PaymentTypeId.ToString()
               }).ToList();

            model.ListOfPaymentTypes.Insert(0, new SelectListItem

            {
                Text = "Choose Payment Type"
            });
            model.CartTotal = CartTotal;
            model.Products = ListOfProducts;

            return View(model);
            
        }

        //Method Name: Payment
        //Purpose of the Method: Method should take you to the Payment view with form to add Payment.
        //Arguments in Method: None.
         [HttpGet]
         [Authorize]
         public async Task<IActionResult> Payment()
        {
            var user = await GetCurrentUserAsync();

            PaymentTypeViewModel model = new PaymentTypeViewModel(_userManager, newContext);

            return View(model);
        }

        //Method Name: Overloaded Payment
        //Purpose of the Method: This is the Overloaded method that actually adds the payments to the Db.
        //Arguments in Method: Takes a new PaymentType object from the form provided and posts it to the database.
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Payment([FromForm]PaymentType paymentType)
        {
            ModelState.Remove("paymentType.User");

            if (ModelState.IsValid)
            {
                /*
                    If all other properties validation, then grab the 
                    currently authenticated user and assign it to the 
                    product before adding it to the db context
                */
                var user = await GetCurrentUserAsync();
                paymentType.User = user;

                newContext.Add(paymentType);

                await newContext.SaveChangesAsync();
                return RedirectToAction("ShoppingCart");
            }
            
            return BadRequest();
        }

        //Method Name: OrderCompleted
        //Purpose of the Method: To change the isCompleted bool from false to true on the active order for this customer and direct the user to the OrderCompleted view.
        //Arguments in Method: None.
        [HttpGet]
        [Authorize]
        public IActionResult OrderCompleted()
        {

            BaseViewModel model = new BaseViewModel(_userManager, newContext);

            return View(model);
        }
        //Method Name: SubmitOrder
        //Purpose of the Method: To change the isCompleted bool from false to true on the active order for this customer and direct the user to the OrderCompleted view.
        //Arguments in Method: None.
        [HttpPatch]
        [Authorize]
        public async Task<IActionResult> SubmitOrder([FromRoute]int id)
        {
            if (id == 0)
            {
                return NotFound(); 
            }
            var user = await GetCurrentUserAsync();
            var activeOrder = await newContext.Order.Where(o => o.IsCompleted == false && o.User==user)
            .SingleOrDefaultAsync();
            activeOrder.PaymentType = newContext.PaymentType.Where(pt => pt.PaymentTypeId == id).SingleOrDefault();
            activeOrder.DateCompleted = DateTime.Today;
            activeOrder.IsCompleted = true;
            newContext.Update(activeOrder);
            await newContext.SaveChangesAsync();

            return Json(id);
        }
    }
}

src/BangazonUserAuth/Controllers/ProductsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using BangazonUserAuth.Data;
using BangazonUserAuth.Models;
using BangazonUserAuth.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace BangazonUserAuth.Controllers
{
    //Class Name: ProductsController
    //Author: Debbie Bourne, Delaine Wendling
    //Purpose of the class: The purpose of this class is to manage the methods that will produce the data and functionality needed for all of the views in the user interface related to products.
    //Methods in Class: Index(), Types(), TypesList(), Single(), New(), Overloaded New(Product product), AddToCart().
    public class ProductsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        private ApplicationDbContext newContext;
        public ProductsController(UserManager<ApplicationUser> userManager, ApplicationDbContext ctx1)
        {
            _userManager = userManager;
            newContext = ctx1;
        }

        // This task retrieves the currently authenticated user
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        //Method Name: Index
        //Purpose of the Method: This method is the first method that is loaded when a user visits Bangazon. This method will get all of the products in the database and show them on the homepage.
        //Arguments in Method: None.
        public async Task<IActionResult> Index()
        {
            AllProductsViewModel model = new AllProductsViewModel(_userManager, newContext);

            model.Products = await newContext.Product.ToListAsync();
 
            return View(model);
        }

        //Method Name: Types
        //Purpose of the Method: This will load all of the ProductTypes from our DB and pass them to the view.
        //Arguments in Method: None.
        public async Task<IActionResult> Types()
        {
            AllProductTypesViewModel model = new AllProductTypesViewModel(_userManager, newContext);
           
            model.ProductTypes = await newContext.ProductType.ToListAsync();

            return View(model);
        }

        //Method Name: TypesList
        //Purpose of the Method: This method returns all products that fall within a ProductType, using the ProductTypeId.
        //Arguments in Method: The ProductTypeId. 
        public async Task<IActionResult> TypesList([FromRoute] int? id)
        {
            if (id == null) 
            {
                return NotFound();
            }
            AllSubProductTypesViewModel model = new AllSubProductTypesViewModel(_userManager, newContext);

            model.SubProductTypes = await newContext.SubProductType.Where(p => p.ProductTypeId == id).ToListAsync();
            model.ProductType = await newContext.ProductType.Where(p => p.ProductTypeId == id).SingleOrDefaultAsync();
            
            if (model.SubProductTypes == null)
            {
                return NotFound();
            }
            return View(model);
        }

        //Method Name: ProductsInSubType
        //Purpose of the Method: This method gets all the products in a selected subtype and returns them.
        //Arguments in Method: Gets the subtypeId from the route.
        public async Task<IActionResult> ProductsInSubType([FromRoute] int id) 
        {
            AllProductsViewModel model = new AllProductsViewModel(_userManager, newContext);

            model.Products =  await newContext.Product.Where(p => p.SubProductTypeId == id).ToListAsync();
            model.SubProductType = await newContext.SubProductType.Where(p => p.SubProductTypeId == id).SingleOrDefaultAsync();


            if (model.Products == null)
            {
                return NotFound();
            }

            return View(model);
        }

        //Method Name: Single
        //Purpose of the Method: This method gets a specific product and returns it to the view.
        //Arguments in Method: The ProductId of the product you wish to pass to the view.
        public async Task<IActionResult> Single([FromRoute] int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            SingleProductViewModel model = new SingleProductViewModel(_userManager, newContext);

            var SingleProduct = await newContext.Product.SingleOrDefaultAsync(p => p.ProductId == id);

            model.Product = SingleProduct;
            model.CustomerName = $"{SingleProduct.User.FirstName} {SingleProduct.User.LastName}";

            if (model.Product == null)
            {
                return NotFound();
            }
            
            return View(model);
        }

        //Method Name: New
        //Purpose of the Method: This method returns the New.cshtml file in the Products folder, which will contain a form to add a new product.
        //Arguments in Method: None.
        [Authorize]
        public async Task<IActionResult> New()
        {
            var user = await GetCurrentUserAsync();
            ProductTypesListViewModel model = new ProductTypesListViewModel(_userManager, newContext);
            return View(model);
        }

        //Method Name: Overloaded New
        //Purpose of the Method: This method takes information from the add product form and posts that information to the database, if it is valid. If the information is invalid, the user will be returned back to the form view. 
        //Arguments in Method: This method takes in an argument of type Product from the form.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> New(Product product)
        {
            if (ModelState.IsValid)
            {
                newContext.Add(product);
                await newContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            //Make sure error messages are present in the view if the view is returned to the customer.
            return BadRequest();
        }

         //Method Name: AddToCart
         //Purpose of the Method: When called, this method should add a product to the current active order. If there isnt a current active order a new one should be made with the active customer.
         //Arguments in Method: The ProductId of the product to add to the active order.
         //Something to note, the methods here must return a json response to the ajax call so the ajax call can redirect the window to index.
         [HttpPost]
         [Authorize]
         public async Task<IActionResult> AddToCart([FromRoute] int id)
         {
            var user = await GetCurrentUserAsync();
            //Get the active customer's order
            var activeOrder = await newContext.Order.Where(o => o.IsCompleted == false && o.User==user).SingleOrDefaultAsync(); 

             // If no active order create one and add the product to it.
             if (activeOrder == null)
             {
                 var order = new Order();
                 order.IsCompleted = false;
                 order.User = user;
                newContext.Add(order);
                 await newContext.SaveChangesAsync();
                 var newOrder = await newContext.Order.Where(o => o.IsCompleted == false && o.User==user).SingleOrDefaultAsync();
                 var lineItem = new LineItem();
                 lineItem.OrderId = newOrder.OrderId;
                 lineItem.ProductId = Convert.ToInt32(id);
                newContext.Add(lineItem);
                 await newContext.SaveChangesAsync();
                 return Json(id);
             }
             else 
             // Add the Product to the existing active order.
             {
                 var lineItem = new LineItem();
                 lineItem.OrderId = activeOrder.OrderId;
                 lineItem.ProductId = Convert.ToInt32(id);
                newContext.Add(lineItem);
                 await newContext.SaveChangesAsync();
                 return Json(id);
             }
         }

        //Method Name: GetSubTypes
        //Purpose of the Method: This method is called when the user changes the Product Type dropdown list to select a larger product category. The method grabs all subTypes within that Product Type and returns them in a Json format. 
        //Arguments in Method: Takes in an integer, which is equal to the ProductTypeId of the selected larger Product Category. 
        [HttpPost]
        public IActionResult GetSubTypes([FromRoute]int id)
        {
            //get sub categories with that product type on them
            var subTypes = newContext.SubProductType.Where(p => p.ProductTypeId == id).ToList();
            return Json(subTypes);
        }
        //Method Name: Error
        //Purpose of the Method: Default error message, return Error view.
        //Arguments in Method: None.
        public IActionResult Error()
        {
            return View();
        }
    }
}

src/BangazonUserAuth/Views/Customers/OrderCompleted.cshtml
@model BangazonUserAuth.ViewModels.BaseViewModel

@{
    ViewData["Title"] = "Thank You";
}

<div class="row text-center thankYou"> <h1>Thank You for ordering with Bangazon!</h1></div>

src/BangazonUserAuth/Views/Customers/Payment.cshtml
@model BangazonUserAuth.ViewModels.PaymentTypeViewModel

@{
    ViewData["Title"] = "New Payment Type";
}

<h1>Add a New Payment Type</h1>

<form asp-action="Payment" method="Post" asp-controller="Customers">
    <div class="form-horizontal">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>    
        
        <div class="form-group">
            <label asp-for="PaymentType.FirstName" class="col-md-2 control-label">First Name</label>
            <div class="col-md-10">
                <input asp-for="PaymentType.FirstName" class="form-control" />
                <span asp-validation-for="PaymentType.FirstName" class="text-danger" />
            </div>
        </div>
        
        <div class="form-group">
            <label asp-for="PaymentType.LastName" class="col-md-2 control-label">Last Name</label>
            <div class="col-md-10">
                <input asp-for="PaymentType.LastName" class="form-control" />
                <span asp-validation-for="PaymentType.LastName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PaymentType.StreetAddress" class="col-md-2 control-label">Street Address</label>
            <div class="col-md-10">
                <input asp-for="PaymentType.StreetAddress" class="form-control" />
                <span asp-validation-for="PaymentType.StreetAddress" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PaymentType.State" class="col-md-2 control-label">State</label>
            <div class="col-md-10">
                <input asp-for="PaymentType.State" class="form-control" />
                <span asp-validation-for="PaymentType.State" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PaymentType.City" class="col-md-2 control-label">City</label>
            <div class="col-md-10">
                <input asp-for="PaymentType.City" class="form-control" />
                <span asp-validation-for="PaymentType.City" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PaymentType.ZipCode" class="col-md-2 control-label">Zip Code</label>
            <div class="col-md-10">
                <input asp-for="PaymentType.ZipCode" class="form-control" />
                <span asp-validation-for="PaymentType.ZipCode" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PaymentType.Processor" class="col-md-2 control-label">Type of card</label>
            <div class="col-md-10">
                <input asp-for="PaymentType.Processor" class="form-control" />
                <span asp-validation-for="PaymentType.Processor" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PaymentType.CardNumber" class="col-md-2 control-label">Card Number</label>
            <div class="col-md-10">
                <input asp-for="PaymentType.CardNumber" class="form-control" />
                <span asp-validation-for="PaymentType.CardNumber" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PaymentType.ExpirationDate" class="col-md-2 control-label">Expiration Date</label>
            <div class="col-md-10">
                <input asp-for="PaymentType.ExpirationDate" class="form-control" />
                <span asp-validation-for="PaymentType.ExpirationDate" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create Payment Type" class="btn btn-default" />
            </div>
        </div>

    </div>
</form>

src/BangazonUserAuth/Views/Customers/ShoppingCart.cshtml
@model BangazonUserAuth.ViewModels.ShoppingCartViewModel

@{
  ViewData["Title"] = "Shopping Cart";
}
<h1> @ViewData["Title"] </h1>
<div class="row text-right">
   @Html.DropDownList("ListOfPaymentTypes")
</div>
<div class ="row text-right">
  <button asp-action="Payment" class="btn btn-danger btn-lg"><a asp-action="Payment">Add Payment</a></button>
</div><br>
<div class ="row text-right">
  <button id="submitOrder" class="btn btn-danger btn-lg">Submit Order</button>
</div>
  <!--Button with Add to Cart on it-->
@foreach (var product in Model.Products)
{

  <div class="row text-left">
    <div class="col-md-4">
      <a asp-action="Single" asp-route-id="@product.ProductId" asp-controller="Products">
        @Html.DisplayFor(modelItem => product.Name)
      </a>
    </div>
    <div>@Html.DisplayFor(modelItem => product.Description)</div>
    <div>@Html.DisplayFor(modelItem => product.Price)</div>
</div>
}
<div class="row">
  <strong>Cart Total:</strong> $@Model.CartTotal
</div>